---

- name: Restart Open VM Tools services
  service:
    name: vmtoolsd
    state: restarted
  when: >
    open_vm_tools_service_started is not defined or
    not open_vm_tools_service_started.changed
